pipeline {
    agent any
    parameters {
        string(name: 'russparameterizedjob', defaultValue: 'master', description: 'Enter the name of the branch to build')
    }
    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "jenkins-maven"
    }
    stages {
        stage('Build') {
            steps {
                // Use the BRANCH_NAME parameter in the git command to checkout the specified branch
                git branch: params.BRANCH_NAME, url: 'https://github.com/cnsidze/java-project.git'
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                success {
                    archiveArtifacts 'target/*.jar'
                }
            }
        }
    }
}
