pipeline {
    agent any
    parameters {
        string(name: 'russparameterizedjob', defaultValue: 'master', description: 'Enter the name of the branch to build')
    }
    environment { 
        registry = "russlltankoua/nginx" 
        registryCredential = 'docker-hub-credentials' 
        dockerImage = '' 
    }
    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "jenkins-maven"
    }
    stages {
        stage('Build') {
            steps {
                // Use the BRANCH_NAME parameter in the git command to checkout the specified branch
                git 'https://github.com/russelltankoua/russ90.git/'
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                success {
                    archiveArtifacts 'target/*.jar'
                }
            }
        }
        stage('Cloning our Git') { 
            steps { 
                git 'https://github.com/russelltankoua/russ90.git/' 
            }
        } 
        stage('Building our image') { 
            steps { 
                script { 
                    dockerImage = docker.build registry + ":$BUILD_NUMBER" 
                }
            } 
        }
        stage('Deploy our image') { 
            steps { 
                script { 
                    docker.withRegistry( '', registryCredential ) { 
                        dockerImage.push() 
                    }
                } 
            }
        }
    }
}
